name: Linux Build

on:
  workflow_call:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Update Submodules
      shell: bash
      working-directory: ${{runner.workspace}}/grpc-labview
      run: git submodule update --init --recursive

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/cmake/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/cmake/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/cmake/build
      shell: bash
      run: make -j 16

    - if: ${{always() }}
      name: Print CMakeTests logs
      run: |
        folder="${{runner.workspace}}/grpc-labview/tests/CMakeTests/logs/"

        # Check if the folder exists
        if [ ! -d "$folder" ]; then
          echo "CMakeTests log folder (grpc-labview/tests/CmakeTests/logs) does not exist."
          echo "Exiting the script."
          exit
        fi

        # Change to the folder
        cd "$folder" || exit

        # Iterate through files and print their contents
        for file in *; do
            if [ -f "$file" ]; then
                cat "$file"
                echo
            fi
        done

    - name: Tar Build Artifacts
      run: >-
        tar -czvf liblabview-grpc-server-linux.tar.gz -C ${{runner.workspace}}/cmake/build
        liblabview_grpc_server.so
        liblabview_grpc_generator.so

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: liblabview-grpc-server-linux
        path: liblabview-grpc-server-linux.tar.gz
        retention-days: 5
